name: Update URLs

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to shorten'
        required: true
        default: ''

jobs:
  update-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install node-fetch
        run: npm install node-fetch

      - name: Update URLs
        run: node scripts/update-urls.cjs ${{ github.event.inputs.url }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
