name: Update URLs

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to shorten'
        required: true
        default: ''

jobs:
  update-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update URLs
        run: node scripts/update-urls.js ${{ github.event.inputs.url }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
